Update

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -21,9 +21,24 @@ jobs:
           username: github_user
           key: ${{ secrets.SSH_MAIN_PRIVATE_KEY }}
           script: |
-            cd /home/github_user/workspace/MiniRag
-            git checkout main
+            cd /home/github_user/workspace/mini-rag
+            git checkout develop
             git pull
             sudo systemctl restart minirag.service
-            echo "Waiting...."
-            sleep 10
+            echo "Waiting..."
+            sleep 20
+
+            for i in {1..6}; do
+              if ss -tuln | grep -q ':80'; then
+                echo "✅ Port 80 is now active."
+                break
+              else
+                echo "⏳ Port 80 not ready yet. Retrying in 5 seconds..."
+                sleep 5
+              fi
+            done
+
+            if ! ss -tuln | grep -q ':80'; then
+              echo "❌ Service failed to start on port 80"
+              exit 1
+            fi
