Update

diff --git a/.github/workflows/deploy-main.yml b/.github/workflows/deploy-main.yml
--- a/.github/workflows/deploy-main.yml
+++ b/.github/workflows/deploy-main.yml
@@ -1,9 +1,9 @@
-name: Deploy Main Branch to Server
+name: Deploy Develop Branch to Server
 
 on:
   push:
     branches:
-      - main
+      - develop
 
 jobs:
   deploy:
@@ -11,28 +11,35 @@ jobs:
 
     steps:
       - name: Checkout code
-        uses: actions/checkout@v3
+        uses: actions/checkout@v4.2.2
 
-      - name: Deploy Locally
-        run: |
-          cd /home/github_user/workspace/MiniRag
-          git checkout develop
-          git pull
-          sudo systemctl restart minirag.service
-          echo "Waiting..."
-          sleep 20
+      - name: Deploy via SSH
+        uses: appleboy/ssh-action@v1.2.2
+        with:
+          host: ${{ secrets.SSH_DEVELOP_HOST_IP }}
+          username: github_user
+          key: ${{ secrets.SSH_DEVELOP_PRIVATE_KEY }}
+          script: |
+            cd /home/github_user/workspace/mini-rag
+            git checkout develop
+            git pull
+            sudo systemctl restart minirag.service
+            echo "Waiting..."
+            sleep 20
 
-          for i in {1..6}; do
-            if ss -tuln | grep -q ':80'; then
-              echo "✅ Port 80 is now active."
-              break
-            else
-              echo "⏳ Port 80 not ready yet. Retrying in 5 seconds..."
-              sleep 5
+            for i in {1..6}; do
+              if ss -tuln | grep -q ':80'; then
+                echo "✅ Port 80 is now active."
+                break
+              else
+                echo "⏳ Port 80 not ready yet. Retrying in 5 seconds..."
+                sleep 5
+              fi
+            done
+
+            if ! ss -tuln | grep -q ':80'; then
+              echo "❌ Service failed to start on port 80"
+              exit 1
             fi
-          done
 
-          if ! ss -tuln | grep -q ':80'; then
-            echo "❌ Service failed to start on port 80"
-            exit 1
-          fi
+
